language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - PYTHONPATH="/home/travis/build/json-transformations/{{cookiecutter.package_name}}"
install: "pip install pytest-cov pytest-pep8 coveralls"
script: py.test --cov={{cookiecutter.package_name}} --pep8
after_success:
- coveralls
